# Use a lightweight official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy entire project
COPY . .

# after COPY . .
RUN python manage.py collectstatic --noinput

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Expose port for Render
EXPOSE 8000

# Start server using Gunicorn and dynamic Render port
CMD ["gunicorn", "fudge_kettle.wsgi:application", "--bind", "0.0.0.0:$PORT"]
