# Generated by Django 5.2.4 on 2025-07-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
